#Edit to fit your analysis


# Hox to run it on bigmemorix : 
# sbatch --wrap="snakemake --snakefile /StarrTrack/StarrTrack_main_snakemake.smk --use-conda --cores 20"
#threads
threads : 15
#Working directory
outdir : '/mnt/thymus/synoSalva/Nori_Processing/bm_process/capstarr/k562_santiago'

# Your input file have to be in input folder then separate cdna from library with proper folders
path_to_files : '/mnt/thymus/synoSalva/Nori_Processing/bm_process/capstarr/k562_santiago/data/input'

#Path to chromosome size file
chr_size_file : '/mnt/thymus/synoSalva/Nori_Processing/bm_process/genome/hg19/hg19.chr_size.txt'

#Path to ref coordinates of captured region : DHS, hProm...
captured_regions_ref : '/mnt/thymus/synoSalva/Nori_Processing/bm_process/genome/captured_regions/hProm.hg19.annotated_id.bed'
